### PR TITLE
Apply doc standards to new Cards endpoint

### LINKED ISSUE #69: wrong type response Accouts.list()
https://github.com/moovfinancial/moov-node/blob/d27d18dfd75ab797aaee7e0c730a1e700079cc43/lib/accounts.js#L383

The type should be Account[] as the response is an array

### PR DESCRIPTION
**Pull request by sethlivingston**
Review with whitespace turned off -- Prettier was applied.

- Renamed `CardExternalInfo` to `LinkCard` to match our conventions
- Renamed errors to match our conventions (Node's conventions, actually)
- Prettierified
- Fixes #69

### CODE REVIEW

File: lib/cards.js [hunk 1]
```diff
@@ -215,40 +213,43 @@ export const CARD_BRAND = {
...
-   async list(accountID) {
-    checkString(accountID).or(Err.AccountID);
+  async list(accountID) {
+    checkString(accountID).or(Err.MISSING_ACCOUNT_ID);
 
     const result = await this.moov
       .got({
         url: `accounts/${accountID}/cards`,
-        method: "GET",
+        method: "POST",
```
Comment (MorganWalkup) [inline lib/cards.js:222]: @sethlivingston The cards list endpoint is a GET, not a POST, right?
https://docs.moov.io/api/#operation/listCards

Comment (sethlivingston) [reply lib/cards.js:222]: Yes, thank you! I'm not sure how that happened.

File: lib/cards.js [hunk 2]
```diff
@@ -83,26 +81,26 @@ export const CARD_BRAND = {
...
- * 
+ *
  * @tag Cards
  */
 /**
- * Card account expiration date
- * @typedef CardExternalInfo
- * @property {CardExpiration} expiration - Card expiration date
+ * Card information collected for acquisition.
+ * @typedef LinkCard
```
Comment (eric-moov) [inline lib/cards.js:97]: Though I like this name better... I wonder if this will cause some issues for those that are using the type already.  Might be limited.  So, probably OK to let this through.  But something to consider when making these sorts of changes.

Comment (sethlivingston) [reply lib/cards.js:97]: @eric-moov That type hasn't been released yet, so we're good. Thanks for checking!

File: lib/helpers/errors.js [hunk 3]
```diff
@@ -1,35 +1,41 @@
...
-  MISSING_CAPABILITIES: "Please provide capabilities.",
-  MISSING_CAPABILITY: "Please provide capability.",
-  MISSING_TRANSFER_ERROR_MESSAGE: "Please provide transfer details.",
-  MISSING_TRANSFER_OPTION_CRITERIA_ERROR_MESSAGE: "Please provide transfer option criteria.",
-  MISSING_COUNTRIES: "Please provide countries.",
-  MISSING_AMOUNTS: "Please provide amounts.",
+  // 1. Keep these errors alphabetized
+  // 2. Do not use variable names -- use phrases (e.g. "bank account ID" not "bankAccountID")
+  // 3. Duplicate the voice and tone used by existing errors when you add a new one
+  // 4. Do not capitialize or use punctuation -- these errors are for developers
```
[the remark this answers is not in the document]
Comment (eric-moov) [reply lib/helpers/errors.js:5]: Somebody did not like the way the errors were previously returned.  hmmm... ;-P

[the remark this answers is not in the document]
Comment (sethlivingston) [reply lib/helpers/errors.js:5]: They had gotten a little... messy :)

**Review by eric-moov — APPROVED** [review]

File: lib/cards.js [hunk 4]
```diff
@@ -215,40 +213,43 @@ export const CARD_BRAND = {
...
-   async list(accountID) {
-    checkString(accountID).or(Err.AccountID);
+  async list(accountID) {
+    checkString(accountID).or(Err.MISSING_ACCOUNT_ID);
 
     const result = await this.moov
       .got({
         url: `accounts/${accountID}/cards`,
         method: "GET",
+        json: card,
```
Comment (paulMery) [inline lib/cards.js:223]: @sethlivingston this might not be expected. unless I am missing something 🤔

Comment (sethlivingston) [reply lib/cards.js:223]: @paulMery Yep that looks like a bug that's been there a while. It's harmless because card is `undefined`, but I'll fix it for the next release. Thanks!
